/*==============================================================*/
/* Nom de SGBD :  MySQL 5.0                                     */
/*                                                              */
/*==============================================================*/


CREATE TABLE SERVICES (
SRVNO SMALLINT  NOT NULL,
SRVNOM VARCHAR(30),
PRIMARY KEY (SRVNO));

CREATE TABLE PROJETS (
PROJNO INT  NOT NULL,
PROJLIB CHAR(11)  NOT NULL  UNIQUE,
SRVNO SMALLINT  NOT NULL,
PRIMARY KEY (PROJNO),
FOREIGN KEY (SRVNO) REFERENCES SERVICES (SRVNO));

CREATE TABLE EMPLOYES (
EMPNO SMALLINT  NOT NULL AUTO_INCREMENT,
EMPNOM VARCHAR(30),
EMPPREN VARCHAR(30),
EMPSEXE CHAR(1)  CHECK(EMPSEXE IN ('M','F')),
EMPSALAIRE DEC(8, 2),
EMPPRIME DEC(6, 2)  DEFAULT 0  CHECK(EMPPRIME < EMPSALAIRE/2),
SRVNO SMALLINT  NOT NULL,
PRIMARY KEY (EMPNO),
FOREIGN KEY (SRVNO) REFERENCES SERVICES (SRVNO))
ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE INTERVENIR (
PROJNO INT  NOT NULL,
EMPNO SMALLINT  NOT NULL,
NBHEURES SMALLINT  NOT NULL  DEFAULT 0,
PRIMARY KEY (PROJNO, EMPNO),
FOREIGN KEY (EMPNO) REFERENCES EMPLOYES (EMPNO),
FOREIGN KEY (PROJNO) REFERENCES PROJETS (PROJNO) );
